### ISSUE TITLE
Convert missing export sales and immaterial assets to 0

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/expat-analysis#203]
This requires an executive decision. But firms with no exports or no immaterial assets might leave these entries blank, rather than write in a 0. @zaveczgergo can you explore the time series properties? Are these missing across all the years of the same firm? Or 0 when non-missing?

```
generate byte zero_missing_positive = 0 if `X' == 0
replace zero_missing_positive = 1 if missing(`X')
replace zero_missing_positive = 2 if `X' > 0 & !missing(`X')
tabulate zero_missing_positive L.zero_missing_positive, missing
```

**Comment by zaveczgergo** [comment]
I did for the three variables with many missing values, please see the log file.

**Comment by zaveczgergo** [comment]
@korenmiklos 

I updated this file, please see the most recent version where I recoded export and immat to 0 when missing. I run some analytics on all imputed versions, see `_imputed` for these. Some questions to be decided by you and Álmos:

1, Should I recode export and immat to 0?

2, And should then I leave lnEx out, because that still has a lot of zeros.

3, Should I code lnIK as 0 for those where immat is 0 (as Álmos proposed for lnIK_0)?

4, Should I use lnQhr instead of ln Qh?

5, TFP_cd and lnQhr still have some missing values. Should we leave them as they are?

6, After these modifications should I use `attgt varlist` or do I have to stick to the loop solution?

**Comment by zaveczgergo** [comment]
I just can not push my files. Password is not working on github anymore (yesterday it did). I tried to create a PAT, but with that when I managed to push, it says, everything is up to date. It ignores my files in `git status` or what I comitted.

**Comment by zaveczgergo** [comment]
GIt issues solves, please see the [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_attgt_missing.log) file.
