### ISSUE TITLE
Split att by calendar time

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/expat-analysis#237]
Create two regression tables with `attgt, aggregate(att) pre(5) post(10)` (same as in event studies) for all outcome variables.

Table 1: `if year <= 2003`

Table 2: `if year>=2004`

**Comment by zaveczgergo** [comment]
In event studies `treatment` is used (in `event_studies.do`), while in other tables we have `treatment` and `treatment2` (e.g. in `est_attgt_tr.do`). I used the former code as asked, please let me know if I should use the latter.

**Comment by zaveczgergo** [comment]
@korenmiklos However, when `att` is used instead of `e` as option for `aggregate`, all estimations are ommitted.

**Comment by zaveczgergo** [comment]
I tried without the `if year`, without `limitcontrol`and all yielded ommitted results with `att`. It is strange because with `post` as 10 and `e ` it yields results. Also if `post` is set at 5 and I have `aggregate(att)`, there are results. Can not it be the case that `aggregate(att)` requires all `post` years to be estimated?

**Comment by zaveczgergo** [comment]
I got rid off `ipw` in the code as well besides to change time frame.
