### ISSUE TITLE
Refer to last year's firing

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/expat-analysis#54]
https://github.com/korenmiklos/expat-analysis/blob/de5d64a291d441ae75b757503e4297430e1c3a43/create_firm_panel.do#L111

**Comment by korenmiklos** [comment]
`gen byte fire = ((job_end >= previous_year) & (job_end < year))`

**Comment by zaveczgergo** [comment]
Managers are not in the panel after they are fired, so the suggested code yields only 0-s (`job_end < year` can never be met). I have to think about how to code `fire` in another way.

**Comment by korenmiklos** [comment]
Then it's probably enough to check `job_end >= previous_year`.

**Comment by zaveczgergo** [comment]
That yields too many 1-s as that is true for almost all years when a manager is there (`job_end` is constant for a `manager_id` and is the last year when a manager is there).
I also tried `bys frame_id_numeric manager_id (year): gen byte fire2 = (job_end >= previous_year) & (_n == _N)` but that is not good neither as codes the last year once again.
I think the problem is that we want to make `fire` to be 1 when a manager is not there anymore (next year). But now we only have the years when the manager is there in the panel. So this issue may be addressed after the collapse somehow.

**Comment by zaveczgergo** [comment]
I know `bys frame_id_numeric (year): gen ceo_spell = sum(hire_ceo | l1.fire_ceo) + 1` may not the good solution because of the holes in the data (and there are indeed holes even after the `collapse` which obtains a firm-year panel from the manager-year panel). But I just wanted to check whether it solves the problem in `test_analysis_sample.do` with cases for  `count if has_expat == 1 & f1.has_expat == 0 & ceo_spell == f1.ceo_spell`: it indeed solves that one, there are zero such cases this way.
